FROM node:22.21.1-alpine

WORKDIR /app

RUN corepack enable

COPY server/package.json server/pnpm-lock.yaml server/pnpm-workspace.yaml ./

RUN pnpm install --frozen-lockfile

COPY server/ ./

EXPOSE 8080

CMD ["pnpm", "run", "dev"]
